# Inspiration: https://github.com/edx/configuration/blob/master/.travis.yml

env: 
  global: 
    - IPOPT_DEFAULT_LINEAR_SOLVER=ma57
    - LD_LIBRARY_PATH=/home/travis/build/libhsl
    - ECOS=/home/travis/build/ecos
    - MOSEK=/home/travis/build/mosek
    - MOSEKLM_LICENSE_FILE=/home/travis/build/testbot/restricted/mosek.lic
    - secure: KvMG4VORV7Ja09shvmsMpiaRMoWqupR76dKxOd7W28I//F4YDIn5ZZefM4aoXsmRgs4G9YqloU8JjVpHutZARmKn2drUwHVMA+96iKb9eDODwZaKXgFYsrQIX5c/OgO8ZpsXynD2daqH3bMK8Mjz1+4fjbFToPFXHggxqQuHm1U=
    - CMAKE_INCLUDE_PATH=/home/travis/build/testbot/restricted/cplex/cplex/include:/home/travis/build/testbot/restricted/cplex/concert/include
    - CMAKE_LIBRARY_PATH=/home/travis/build/testbot/restricted/cplex/cplex/lib/x86-64_sles10_4.1/static_pic/:/home/travis/build/testbot/restricted/cplex/concert/lib/x86-64_sles10_4.1/static_pic/
    - ILOG_LICENSE_FILE=/home/travis/build/testbot/restricted/cplex/access.ilm
    - WORHP=/home/travis/build/testbot/restricted/worhp
    - WORHP_LICENSE_FILE=/home/travis/build/testbot/restricted/worhp/unlocked.lic
    - SNOPT=/home/travis/build/snopt7
    - MATLABPATH=/home/travis/build/matlab-install
    - MATLAB_ROOT=/home/travis/build/matlab
    - MATLABRELEASE=R2014b
    - CLANG=/home/travis/build/clang

matrix:
  include:
    - compiler: gcc
      os: linux
      install:
        - setup_precise
      env: TESTMODE=full_valgrind
      script:
        - sudo apt-get install valgrind -y
        - mkdir build
        - pushd build
        - cmake -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=ON -DWITH_OOQP=ON -DWITH_DOC=ON -DWITH_EXAMPLES=OFF  ..
        - make -j2
        - sudo make -j2 install
        - popd
        - python -c "from casadi.tools import *;loadAllCompiledPlugins()"
        - pushd test/python && ls -1 [n-z]*.py | grep -v helpers.py | xargs rm && popd
        - pushd test && make unittests_py_valgrind && popd
    - compiler: gcc
      os: linux
      install:
        - setup_precise
      env: TESTMODE=full_valgrind
      script:
        - sudo apt-get install valgrind -y
        - mkdir build
        - pushd build
        - cmake -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=ON -DWITH_OOQP=ON -DWITH_DOC=ON -DWITH_EXAMPLES=OFF ..
        - make -j2
        - sudo make -j2 install
        - popd
        - python -c "from casadi.tools import *;loadAllCompiledPlugins()"
        - pushd test/python && ls -1 [a-m]*.py | grep -v helpers.py | xargs rm && popd
        - pushd test && make unittests_py_valgrind && popd
    - compiler: gcc
      os: linux
      install:
        - setup_precise
      env: TESTMODE=full_remainder
      script:
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=ON -DWITH_OOQP=ON -DWITH_PROFILING=ON -DWITH_DOC=ON -DWITH_EXAMPLES=ON -DWITH_COVERAGE=ON -DWITH_EXTRA_WARNINGS=ON -DWITH_PYTHON=ON -DWITH_JSON=ON ..
        - make -j2
        - sudo make -j2 install
        - popd
        - sudo apt-get install python-ipdb graphviz python-lxml texlive-science texlive-latex-base texlive-latex-recommended texlive-latex-extra -y
        - sudo pip install pydot2
        - python -c "from casadi.tools import *;loadAllCompiledPlugins()"
        - pushd test && make trunktesterbot_no_unittests_py && popd
        - pushd build && travis_wait make json && popd

    - compiler: gcc
      os: linux
      install:
        - setup_precise
      env: TESTMODE=full_slow
      script:
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=ON -DWITH_OOQP=ON -DWITH_DOC=ON -DWITH_EXAMPLES=OFF -DWITH_EXTRA_WARNINGS=ON ..
        - make -j2
        - sudo make -j2 install
        - popd
        - python -c "from casadi.tools import *;loadAllCompiledPlugins()"
        
        # travis-wait seems to stop at 20 mins, regardless if output is being generated
        - (while true ; do sleep 60 ; echo "ping" ; done ) &
        
        - pushd test && make unittests_py_slow && popd
    - compiler: gcc
      os: linux
      install:
        - setup_precise
      env: TESTMODE=docs
      script:
        - set -e
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_JSON=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DCMAKE_BUILD_TYPE=Debug -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=ON -DWITH_OOQP=ON -DWITH_PROFILING=ON -DWITH_DOC=ON -DWITH_EXAMPLES=ON -DWITH_COVERAGE=ON -DWITH_EXTRA_WARNINGS=ON ..
        - make -j2
        - sudo make -j2 install
        - popd
        - sudo pip install texttable
        - sudo pip install pydot2
        - sudo apt-get install graphviz python-lxml python-ipdb python-docutils doxygen -y
        - pushd docs/api && make doxexport | grep -v "file loc from" && popd
        
        # Let's verify that we can still compile
        - pushd build && make && sudo make -j2 install && make json && popd
        - python -c "import doctest;import casadi;assert doctest.testmod(casadi.casadi,verbose=True).failed==0"
        - git stash && git checkout $TRAVIS_BRANCH && git pull origin $TRAVIS_BRANCH && git stash pop || allowfail 1 && sh /home/travis/build/testbot/helpers/acommit.sh "automatic documentation update" && git push git@github.com:casadi/casadi.git $TRAVIS_BRANCH
    - compiler: clang
      os: linux
      install:
        - setup_precise
      env: TESTMODE=minimal
      script:
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=ON -DWITH_PYTHON=ON -DWITH_JSON=ON ..
        - make
        - sudo make install
        - popd
        - python -c "from casadi.tools import *;loadAllCompiledPlugins()"
        - pushd test && make unittests_py examples_code_py && popd
    - compiler: gcc
      os: linux
      dist: trusty
      language: generic
      install:
        - setup_trusty
      env: TESTMODE=minimal
      script:
        - |
          cat <<EOF | sudo tee --append  /etc/apt/sources.list
          deb-src http://archive.ubuntu.com/ubuntu vivid main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu vivid main restricted universe multiverse
        - |
          cat <<EOF | sudo tee /etc/apt/preferences.d/mytest
          Package: *
          Pin: release n=trusty
          Pin-priority: 700
          Package: *
          Pin: release n=vivid
          Pin-priority: 600
        - sudo apt-get update -q
        - sudo apt-get install -q -y opencl-headers ocl-icd-opencl-dev ocl-icd-libopencl1
        - sudo apt-get -t vivid install pocl-opencl-icd
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=ON -DWITH_PYTHON=ON -DWITH_JSON=ON ..
        - make
        - sudo make install
        - popd
        - python -c "from casadi.tools import *;loadAllCompiledPlugins()"
        #- source /home/travis/build/testbot/restricted/env.sh
        #- ssh-keyscan $GATE_SERVER >> ~/.ssh/known_hosts
        #- whoami
        #- echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA3mEl1i8wiojyJdJnwrmC3RTWCIGgUM4lmtWNWu4p4QyiBry2iB7y2qno48pZqkV/EFRsyWWeEDvbdA4etYlceKZaGJFAdqJig/247qPbamU5W5++d7zkGwA5nQDH147/+JMYk4na9RoGl2iOHMyxi7Wq0WkN11u0Slp2awluvV9UXpBl/XD74eYmUfOFop6y+Hkg/K2hyytg8vAkp33x/vy8JxSK93vbnLGsrVOVjp6Epf7Jo2C8ZHX9eVL2sfi7icjNbt6s9AnU076tBURBIEQbg+Sa8nK7v6zzJNZbn9G85t0M64BKMvcRH1BXf0VvIeBQs/yv9uZLaC9SFvj+4Q== u0052373@xen-vm03.mech.kuleuven.be" >> ~/.ssh/authorized_keys
        #- (while true ; do sleep 60 ; echo "ping" ; done ) &
        #- ssh -i /home/travis/build/testbot/id_rsa_travis $USER_GATE@$GATE_SERVER -R 19922:localhost:22 -N
        - pushd test/python && python function.py && popd
        - pushd test && make unittests_py examples_code_py && popd
    - compiler: gcc
      os: linux
      install:
        - setup_precise
      env: TESTMODE=minimal
      script:
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_DEPRECATED_FEATURES=OFF -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=ON -DWITH_PYTHON=ON -DWITH_JSON=ON ..
        - make
        - sudo make install
        - popd
        - python -c "from casadi.tools import *;loadAllCompiledPlugins()"
        - pushd test && make unittests_py examples_code_py && popd
    - compiler: gcc
      os: linux
      install:
        - setup_precise
      env: TESTMODE=quick
      script:
        - sudo echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
        - sudo apt-get install python-pyparsing libhunspell-dev oracle-java7-installer -y
        - sudo pip install hunspell
        - wget https://www.languagetool.org/download/LanguageTool-2.7.zip
        - unzip LanguageTool-2.7.zip
        - mypwd=`pwd`
        - export languagetool="$mypwd/LanguageTool-2.7"
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_WORHP=ON -DWITH_SLICOT=ON -DWITH_OOQP=ON -DWITH_WERROR=ON -DWITH_EXTRA_WARNINGS=ON ..
        - make lint
        - export languagetool="$mypwd/LanguageTool-2.7" make spell
        - popd && pushd misc && python autogencode.py && popd
        - sh /home/travis/build/testbot/helpers/acommit.sh "automatic code generation"
        - git pull
        - git config --global push.default simple
        - git remote set-url origin git@github.com:casadi/casadi.git
        - ssh-agent bash -c 'ssh-add /home/travis/build/testbot/id_rsa_travis; git push origin HEAD:$TRAVIS_BRANCH'
      after_success:
        - cd /home/travis/build/
        - git clone git@github.com:casadi/binaries.git
        - pushd binaries && git checkout run && git submodule init && git submodule update || allowfail 1 && popd
        - pushd binaries/casadi && git checkout $TRAVIS_COMMIT && popd
        - pushd binaries && git commit -a -m "automatic runner commit $TRAVIS_COMMIT" && git push origin run && popd

    - os: osx
      env: TESTMODE=minimal
      compiler: clang
      before_script:
        - brew update
        - brew tap homebrew/science
        - brew outdated swig ; brew install swig
        #- brew install swig pkg-config
        #- brew doctor
        - sudo easy_install pip
        - sudo pip install ipython matplotlib numpy scipy
      script:
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_WORHP=ON -DWITH_SLICOT=ON -DWITH_PYTHON=ON -DWITH_JSON=ON ..
        - make
        - sudo make install
        - popd
        - python -c "from casadi.tools import *;loadAllCompiledPlugins()"
        - pushd test && make unittests_py && popd

    - compiler: gcc
      os: linux
      env: NEEDMATLAB=1
      install:
        - setup_precise
      script:

        # travis-wait seems to stop at 20 mins, regardless if output is being generated
        - (while true ; do sleep 60 ; echo "ping" ; done ) &

        - pushd /home/travis/build/
        - testbot/recipes/fetch.sh matlab$MATLABRELEASE.tar.gz
        - mkdir matlab && tar -xf matlab$MATLABRELEASE.tar.gz -C matlab
        - popd
        - mkdir build
        - pushd build
        - PATH=/home/travis/build/swig_matlab/bin:/home/travis/build/swig_matlab/share:$PATH cmake  -DOLD_LLVM=ON -DCMAKE_INSTALL_PREFIX=/home/travis/build/matlab-install -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_DEEPBIND=ON -DWITH_MATLAB=ON -DWITH_WORHP=ON -DWITH_SLICOT=ON -DWITH_OOQP=ON -DWITH_PROFILING=ON -DWITH_DOC=ON -DWITH_EXAMPLES=ON -DWITH_COVERAGE=ON -DWITH_EXTRA_WARNINGS=ON -DWITH_JSON=ON ..
        - make -j2
        - sudo make -j2 install
        - popd
        - source /home/travis/build/testbot/restricted/env.sh
        - sudo bash -c "echo '127.0.0.1	$FLEX_SERVER' >> /etc/hosts;echo '127.0.0.1	$FLEX_HOSTNAME' >> /etc/hosts"
        - sudo hostname $FLEX_HOSTNAME
        - mkdir -p ~/.matlab/${MATLABRELEASE}_licenses/
        - echo -e "SERVER $FLEX_SERVER ANY 1715\nUSE_SERVER" > ~/.matlab/${MATLABRELEASE}_licenses/license.lic
        - ssh-keyscan $GATE_SERVER >> ~/.ssh/known_hosts
        - ssh -i /home/travis/build/testbot/id_rsa_travis $USER_GATE@$GATE_SERVER -L 1701:$FLEX_SERVER:1701 -L 1719:$FLEX_SERVER:1719 -L 1718:$FLEX_SERVER:1718 -L 2015:$FLEX_SERVER:2015 -L 1815:$FLEX_SERVER:1815 -L 1715:$FLEX_SERVER:1715 -N &
        - sleep 3
        - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make unittests_matlab && popd
branches:
  except:
    - /.*appveyor.*/
    
before_install:
  - set -e
  - set -o pipefail  # otherwise, piping with grep discards exit statuses
  - pushd ../../ && git clone https://github.com/casadi/testbot.git
  - source testbot/shellhelpers
  - popd
  - |
    function unpack {
      if [ "$1"==*.tar.gz ]; then
        tar -xf $1 -C $2
      elif [ "$1"==*7z ]; then
        7za e $1 -o$2 -y
      fi
    }
    function obtain {
      travis_retry testbot/recipes/fetch.sh $1 && mkdir $2 && tar -xf $1 -C $2 && rm $1
    }
  - |
    function setup_precise {
      sudo /etc/init.d/mysql stop
      sudo /etc/init.d/postgresql stop
      
      # We need some more recent packages
      sudo add-apt-repository ppa:umn-claoit-rce/compute-packages -y
      sudo add-apt-repository ppa:baltix-members/ppa -y #  for libslicot-dev
      sudo add-apt-repository ppa:nodakai/valgrind -y
      sudo add-apt-repository ppa:kedazo/doxygen-updates-precise -y
      sudo add-apt-repository ppa:webupd8team/java -y
      sync
      free -t -m
    }
  - |
    function setup_trusty {
      echo 12
    }
    
before_script:
  - pushd ../../
  - sudo apt-get update -qq
  - sudo apt-get install p7zip-full python-dev -y
  - pushd testbot && recipes/setup.sh && popd
  - obtain libhsl.tar.gz libhsl
  - obtain clang.tar.gz clang
  - travis_retry testbot/recipes/fetch.sh mosek7.tar.bz2 && tar -xf mosek7.tar.bz2 && rm mosek7.tar.bz2
  - git clone https://github.com/embotech/ecos.git && pushd ecos && make && popd
  - obtain snopt7.tar.gz snopt7
  - mkdir -p /home/travis/build/casadi/testbot
  - |
    if [ $NEEDMATLAB ]
    then
      swig_matlab_file=`python testbot/helpers/gitmatch.py testbot/recipes/swig_matlab.yaml /home/travis/build/casadi/casadi`
      travis_retry testbot/recipes/fetch.sh ${swig_matlab_file}.tar.gz && mkdir swig_matlab && tar -xf ${swig_matlab_file}.tar.gz -C swig_matlab && rm ${swig_matlab_file}.tar.gz
      pushd /home/travis/build/casadi/testbot && ln -s  /home/travis/build/swig_matlab  swig-matlab-install  && popd
    else
      travis_retry testbot/recipes/fetch.sh swig.tar.gz && mkdir swig && tar -xf swig.tar.gz -C swig && rm swig.tar.gz
      pushd /home/travis/build/casadi/testbot && ln -s  /home/travis/build/swig  swig-install  && popd
    fi
  - export PATH=/home/travis/build/swig/bin:$PATH
  - pushd testbot/restricted/cplex && mkdir cplex && tar -xf cplex12.4.tar.gz -C cplex && mkdir concert && tar -xf cplex12.4-concert.tar.gz -C concert && rm cplex12.4-concert.tar.gz && popd
  - pushd testbot/restricted && mkdir -p worhp && cd  worhp && 7za e ../libworhp_debian7_amd64_gcc47_1.7-12970f3.7z -y && popd
  - popd
  - sudo apt-get update -qq
  - sudo apt-get install -q -y binutils gcc g++ gfortran git cmake liblapack-dev ipython python-dev python-numpy python-scipy python-matplotlib coinor-libipopt-dev libmumps-seq-dev libblas-dev liblapack-dev libslicot-dev libxml2-dev
  - sudo pip install github3.py
 
after_failure:
  - pushd /home/travis/build/testbot/ && python -c "from github3 import login;from testbotcredentials import TestBotCredentials;tbc = TestBotCredentials();login(*tbc.github).repository('casadi','casadi').create_comment(sha='$TRAVIS_COMMIT',body='Failure reported by [travis](https://travis-ci.org/casadi/casadi/jobs/$TRAVIS_JOB_ID) in $TRAVIS_COMMIT_RANGE -- $TRAVIS_TEST_RESULT')" && popd


language: cpp

