# Inspiration: https://github.com/edx/configuration/blob/master/.travis.yml
env: 
  global: 
    - IPOPT_DEFAULT_LINEAR_SOLVER=ma57
    - MOSEKLM_LICENSE_FILE=/home/travis/build/testbot/restricted/mosek.lic
    - secure: KvMG4VORV7Ja09shvmsMpiaRMoWqupR76dKxOd7W28I//F4YDIn5ZZefM4aoXsmRgs4G9YqloU8JjVpHutZARmKn2drUwHVMA+96iKb9eDODwZaKXgFYsrQIX5c/OgO8ZpsXynD2daqH3bMK8Mjz1+4fjbFToPFXHggxqQuHm1U=
    - CMAKE_INCLUDE_PATH=/home/travis/build/testbot/restricted/cplex/cplex/include:/home/travis/build/testbot/restricted/cplex/concert/include
    - CMAKE_LIBRARY_PATH=/home/travis/build/testbot/restricted/cplex/cplex/lib/x86-64_sles10_4.1/static_pic/:/home/travis/build/testbot/restricted/cplex/concert/lib/x86-64_sles10_4.1/static_pic/
    - ILOG_LICENSE_FILE=/home/travis/build/testbot/restricted/cplex/access.ilm
    - WORHP=/home/travis/build/testbot/restricted/worhp
    - WORHP_LICENSE_FILE=/home/travis/build/testbot/restricted/worhp/unlocked.lic
    - SNOPT=/home/travis/build/snopt75
    - MATLABPATH=/home/travis/build/matlab-install
    - MATLAB_ROOT=/home/travis/build/matlab
    - MATLABRELEASE=R2014b
    - SLURP_OS=trusty

before_script:
  - set -e
  - set -o pipefail  # otherwise, piping with grep discards exit statuses





matrix:
  include:
    - compiler: gcc
      os: linux
      dist: trusty
      language: generic
      env: TESTMODE=valgrind
      script:
        - sudo apt-get install valgrind libgomp1 -y
        - mkdir build
        - pushd build
        - cmake -DWITH_OPENMP=ON -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=OFF -DWITH_OOQP=ON -DWITH_PROFILING=ON -DWITH_DOC=ON -DWITH_EXAMPLES=ON -DWITH_COVERAGE=ON -DWITH_EXTRA_WARNINGS=ON -DWITH_PYTHON=ON -DWITH_JSON=ON ..

        - make -j2
        - sudo make -j2 install
        - popd
        - python -c "from casadi.tools import *;loadAllCompiledPlugins()"
        - pushd test && make unittests_py_valgrind && popd
      after_success:
        - cd build
        - git clone https://github.com/jgillis/cpp-coveralls.git
        - pushd cpp-coveralls && sudo python setup.py install && popd
        - coveralls --verbose --root .. --exclude swig -E '.*cxx' -E '.*CMakeFiles.*' -E '.*casadiPYTHON_wrap.*' -E '.*lib.*' -E '.*_export.*'  --exclude experimental --exclude _temp.cc --exclude docs --exclude codegen --exclude external_packages --exclude cmake --exclude test --gcov-options '\-lp'
    - compiler: gcc
      os: linux
      dist: trusty
      language: generic
      env: TESTMODE=full
      script:
        - sudo apt-get install valgrind libgomp1 -y
        - mkdir build
        - pushd build
        - cmake -DWITH_OPENMP=ON -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=OFF -DWITH_OOQP=ON -DWITH_PROFILING=ON -DWITH_DOC=ON -DWITH_EXAMPLES=ON -DWITH_COVERAGE=ON -DWITH_EXTRA_WARNINGS=ON -DWITH_PYTHON=ON -DWITH_JSON=ON ..

        - make -j2
        - sudo make -j2 install
        - popd
        - sudo apt-get install python-ipdb graphviz python-lxml texlive-science texlive-latex-base texlive-latex-recommended texlive-latex-extra -y
        - sudo pip install pydot2
        # travis-wait seems to stop at 20 mins, regardless if output is being generated
        - (while true ; do sleep 60 ; echo "ping" ; done ) &

        - pushd test && make trunktesterbot_no_unittests_py && popd
        - pushd test && make unittests_py_slow && popd
        - pushd build && make json && popd
      after_success:
        - cd build
        - git clone https://github.com/jgillis/cpp-coveralls.git
        - pushd cpp-coveralls && sudo python setup.py install && popd
        - coveralls --verbose --root .. --exclude swig -E '.*cxx' -E '.*CMakeFiles.*' -E '.*casadiPYTHON_wrap.*' -E '.*lib.*' -E '.*_export.*'  --exclude experimental --exclude _temp.cc --exclude docs --exclude codegen --exclude external_packages --exclude cmake --exclude test --gcov-options '\-lp'
    - compiler: gcc
      os: linux
      dist: trusty
      language: generic
      env:
        - TESTMODE=full-py3
        - WITH_PYTHON3=ON
      script:
        - sudo apt-get install cmake valgrind libgomp1 python3-dev python3-numpy python3-scipy python3-matplotlib python3-setuptools -y
        - sudo easy_install3 pip==7.1.2
        - mkdir build
        - pushd build
        - cmake --version
        - python3 --version
        - cmake -DWITH_OPENMP=OFF -DCMAKE_BUILD_TYPE=Debug -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=OFF -DWITH_OOQP=ON -DWITH_PROFILING=ON -DWITH_DOC=ON -DWITH_EXAMPLES=ON -DWITH_EXTRA_WARNINGS=ON -DWITH_PYTHON=ON -DWITH_PYTHON3=ON -DWITH_JSON=ON ..

        - make -j2
        - sudo make -j2 install
        - popd
        - python3 -c "from casadi.tools import *;loadAllCompiledPlugins()"
        
        #- (while true ; do sleep 60 ; echo "ping" ; done ) &
        #- source /home/travis/build/testbot/restricted/env.sh
        #- ssh-keyscan $GATE_SERVER >> ~/.ssh/known_hosts
        #- whoami
        #- echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA3mEl1i8wiojyJdJnwrmC3RTWCIGgUM4lmtWNWu4p4QyiBry2iB7y2qno48pZqkV/EFRsyWWeEDvbdA4etYlceKZaGJFAdqJig/247qPbamU5W5++d7zkGwA5nQDH147/+JMYk4na9RoGl2iOHMyxi7Wq0WkN11u0Slp2awluvV9UXpBl/XD74eYmUfOFop6y+Hkg/K2hyytg8vAkp33x/vy8JxSK93vbnLGsrVOVjp6Epf7Jo2C8ZHX9eVL2sfi7icjNbt6s9AnU076tBURBIEQbg+Sa8nK7v6zzJNZbn9G85t0M64BKMvcRH1BXf0VvIeBQs/yv9uZLaC9SFvj+4Q== u0052373@xen-vm03.mech.kuleuven.be" >> ~/.ssh/authorized_keys
        #- ssh -i /home/travis/build/testbot/id_rsa_travis $USER_GATE@$GATE_SERVER -R 19922:localhost:22 -N
        #- pushd test && make unittests_py_valgrind && popd
        - sudo apt-get install graphviz python3-lxml texlive-science texlive-latex-base texlive-latex-recommended texlive-latex-extra -y
        - sudo pip3 install pydot3
        # travis-wait seems to stop at 20 mins, regardless if output is being generated
        - (while true ; do sleep 60 ; echo "ping" ; done ) &

        #- pushd test && make trunktesterbot_no_unittests_py && popd
        #- pushd test && make unittests_py_slow && popd
        #- pushd build && make json && popd
        - pushd test && make unittests_py && popd
        - pushd test && make unittests_py_slow && popd
        - pushd test && make examples_code_py && popd
        - pushd test && make user_guide_snippets_py && popd
        - pushd test && make examples_indoc_py && popd
        
    - compiler: gcc
      os: linux
      dist: trusty
      language: generic
      env: TESTMODE=docs
      script:
        - set -e
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_JSON=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DCMAKE_BUILD_TYPE=Debug -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=OFF -DWITH_OOQP=ON -DWITH_PROFILING=ON -DWITH_DOC=ON -DWITH_EXAMPLES=ON -DWITH_COVERAGE=ON -DWITH_EXTRA_WARNINGS=ON ..
        - make -j2
        - sudo make -j2 install
        - popd
        - sudo pip install texttable
        - sudo pip install pydot2
        - sudo apt-get install graphviz python-lxml python-ipdb python-docutils doxygen -y
        - pushd docs/api && make doxexport | grep -v "file loc from" && popd
        
        # Let's verify that we can still compile
        - pushd build && make && sudo make -j2 install && make json && popd
        - python -c "import doctest;import casadi;assert doctest.testmod(casadi.casadi,verbose=True).failed==0"
        - |
          if [[ $TRAVIS_BRANCH == *develop* || $TRAVIS_BRANCH == *release* ]]
          then
            git stash && git checkout $TRAVIS_BRANCH && git pull origin $TRAVIS_BRANCH && git stash pop || allowfail 1 && test $(git status --porcelain | grep UU | wc -c) -eq 0 && sh /home/travis/build/testbot/helpers/acommit.sh "automatic documentation update" && git push git@github.com:casadi/casadi.git $TRAVIS_BRANCH
          fi
    - compiler: clang
      os: linux
      dist: trusty
      language: generic
      env: TESTMODE=minimal
      script:
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=OFF -DWITH_PYTHON=ON -DWITH_JSON=ON ..
        - make
        - sudo make install
        - popd
        - python -c "from casadi.tools import *;loadAllCompiledPlugins()"
        - pushd test && make unittests_py examples_code_py && popd
    - compiler: gcc
      os: linux
      dist: trusty
      language: generic
      env: TESTMODE=minimal
      script:
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_DEPRECATED_FEATURES=OFF -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=OFF -DWITH_PYTHON=ON -DWITH_JSON=ON ..
        - make
        - sudo make install
        - popd
        - python -c "from casadi.tools import *;loadAllCompiledPlugins()"
        - pushd test && make unittests_py examples_code_py && popd
    - compiler: gcc
      os: linux
      dist: trusty
      language: generic
      env: TESTMODE=minimal
      script:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
        - sudo apt-get install gcc-6 g++-6
        - export CC=gcc-6
        - export CXX=g++-6
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_DEPRECATED_FEATURES=OFF -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_PYTHON=ON -DWITH_WORHP=ON -DWITH_SLICOT=OFF -DWITH_PYTHON=ON -DWITH_JSON=ON ..
        - make
        - sudo make install
        - popd
        - python -c "from casadi.tools import *;loadAllCompiledPlugins()"
        - pushd test && make unittests_py examples_code_py && popd
    - compiler: gcc
      os: linux
      dist: trusty
      language: generic
      env: TESTMODE=quick
      script:
        - sudo add-apt-repository ppa:webupd8team/java -y
        - sudo apt-get update -qq
        - sudo echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
        - sudo apt-get install python-pyparsing libhunspell-dev oracle-java7-installer -y
        - sudo pip install hunspell
        - wget https://www.languagetool.org/download/LanguageTool-2.7.zip
        - unzip LanguageTool-2.7.zip
        - mypwd=`pwd`
        - export languagetool="$mypwd/LanguageTool-2.7"
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_WORHP=ON -DWITH_SLICOT=OFF -DWITH_OOQP=ON -DWITH_WERROR=ON -DWITH_EXTRA_WARNINGS=ON ..
        - make lint
        - export languagetool="$mypwd/LanguageTool-2.7" make spell
        - popd && pushd misc && python autogencode.py && popd
        - sh /home/travis/build/testbot/helpers/acommit.sh "automatic code generation"
        - git pull
        - git config --global push.default simple
        - git remote set-url origin git@github.com:casadi/casadi.git
        - ssh-agent bash -c 'ssh-add /home/travis/build/testbot/id_rsa_travis; git push origin HEAD:$TRAVIS_BRANCH'
      after_success:
        - cd /home/travis/build/
        - git clone git@github.com:casadi/binaries.git
        - pushd binaries && git checkout run && git submodule init && git submodule update || allowfail 1 && popd
        - pushd binaries/casadi && git checkout $TRAVIS_COMMIT && popd
        - |
          if ! [[ $TRAVIS_BRANCH == *test* ]]
          then
          pushd binaries && git commit -a -m "automatic runner commit $TRAVIS_COMMIT" && git push origin run && popd
          fi
    - os: osx
      env: TESTMODE=minimal SLURP_OS=osx
      compiler: clang
      before_install:
        - brew update
        - brew tap homebrew/science
        - brew outdated swig ; brew install swig
        #- brew outdated pkg-config || brew install pkg-config
        #- brew doctor
        - sudo easy_install pip
        - sudo pip install ipython matplotlib numpy scipy
      script:
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_WORHP=ON -DWITH_SLICOT=OFF -DWITH_PYTHON=ON -DWITH_JSON=ON ..
        - make
        - sudo make install
        - popd
        - python -c "from casadi.tools import *;loadAllCompiledPlugins()"
        - pushd test && make unittests_py && popd

    - compiler: gcc
      os: linux
      dist: trusty
      language: generic
      env: NEEDMATLAB=1
      script:
        - sudo apt-get install -y gcc-4.7 g++-4.7 gfortran-4.7
        - export CC=gcc-4.7
        - export CXX=g++-4.7

        # travis-wait seems to stop at 20 mins, regardless if output is being generated
        - (while true ; do sleep 60 ; echo "ping" ; done ) &

        - swig -version
        - pushd /home/travis/build/
        - testbot/recipes/fetch.sh matlab$MATLABRELEASE.tar.gz
        - mkdir matlab && tar -xf matlab$MATLABRELEASE.tar.gz -C matlab
        - popd
        - mkdir build
        - pushd build
        - cmake  -DOLD_LLVM=ON -DCMAKE_INSTALL_PREFIX=/home/travis/build/matlab-install -DWITH_CLANG=ON -DWITH_ECOS=ON -DWITH_MOSEK=ON -DWITH_DEEPBIND=ON -DWITH_MATLAB=ON -DWITH_WORHP=ON -DWITH_SLICOT=OFF -DWITH_OOQP=ON -DWITH_PROFILING=ON -DWITH_DOC=ON -DWITH_EXAMPLES=ON -DWITH_COVERAGE=ON -DWITH_EXTRA_WARNINGS=ON -DWITH_JSON=ON ..
        - make -j2
        - sudo make -j2 install
        - popd
        - matlabtunnel
        - pushd test && PATH=/home/travis/build/matlab/bin/:$PATH make matlab && popd
branches:
  except:
    - /.*appveyor.*/

before_install:
  - pushd ../../ && git clone https://github.com/casadi/testbot.git
  - pushd testbot && git checkout merged && source recipes/setup.sh && popd
  - sudo apt-get install p7zip-full -y
  - |
    if [ $NEEDMATLAB ]
    then
      export SLURP_GCC=4.7
      slurp swig_matlab
    else
      slurp swig
    fi

  - slurp hsl
  - slurp clang
  - travis_retry testbot/recipes/fetch.sh mosek7.tar.bz2 && tar -xf mosek7.tar.bz2 && rm mosek7.tar.bz2
  - slurp ecos
  - travis_retry testbot/recipes/fetch.sh snopt75.tar.gz && mkdir snopt75 && tar -xf snopt75.tar.gz -C snopt75 && rm snopt75.tar.gz

  - pushd testbot/restricted/cplex && mkdir cplex && tar -xf cplex12.4.tar.gz -C cplex && mkdir concert && tar -xf cplex12.4-concert.tar.gz -C concert && rm cplex12.4-concert.tar.gz && popd
  - pushd testbot/restricted && mkdir -p worhp && cd  worhp && 7za e ../libworhp_debian7_amd64_gcc47_1.7-12970f3.7z -y && popd
  - slurp bonmin
  - popd
  - sudo apt-get update -qq
  - sudo apt-get install -q -y binutils gcc g++ gfortran git cmake liblapack-dev liblapack3 libblas3 ipython python-dev python-numpy python-scipy python-matplotlib coinor-libipopt-dev libmumps-seq-dev libxml2-dev
  - sudo pip install github3.py
 
after_failure:
  - pushd /home/travis/build/testbot/ && python -c "from github3 import login;from testbotcredentials import TestBotCredentials;tbc = TestBotCredentials();login(*tbc.github).repository('casadi','casadi').create_comment(sha='$TRAVIS_COMMIT',body='Failure reported by [travis](https://travis-ci.org/casadi/casadi/jobs/$TRAVIS_JOB_ID) in $TRAVIS_COMMIT_RANGE -- $TRAVIS_TEST_RESULT')" && popd

