# This action generates the documentation and then deploys it to the `gh-pages` branch.

name: Documentation & Coverage

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Cache the doxygen executable
    - uses: actions/cache@v2
      with:
        path: |
          /tmp/doxygen
          /tmp/lcov
        key: ${{ runner.os }}-doc-${{ hashFiles('scripts/ci/install-doxygen.sh') }}-${{ hashFiles('scripts/ci/install-lcov.sh') }}
    
    - name: Install Graphviz/Dot and LCOV Perl dependencies
      run: sudo apt-get install graphviz libjson-perl libperlio-gzip-perl perl

    - name: Install LCOV
      run: |
        ./scripts/ci/install-lcov.sh /tmp/lcov
        echo "/tmp/lcov/bin" >> $GITHUB_PATH

    # Download and build doxygen (if not cached already)
    - name: Install Doxygen
      run: |
        ./scripts/ci/install-doxygen.sh /tmp/doxygen
        echo "/tmp/doxygen/bin" >> $GITHUB_PATH

    - name: Show Doxygen version
      run: |
        which doxygen
        doxygen --version

    # Install GoogleTest and Eigen
    - uses: actions/cache@v2
      with:
        path: "/tmp/lib-install/gtest"
        key: ${{ runner.os }}-${{ hashFiles('scripts/ci/install-gtest.sh') }}
    - name: Install Google Test
      run: ./ci/install-gtest.sh /tmp/lib-install/gtest
      working-directory: scripts
    - uses: actions/cache@v2
      with:
        path: "/tmp/lib-install/eigen"
        key: ${{ runner.os }}-${{ hashFiles('scripts/ci/install-eigen.sh') }}
    - name: Install Eigen
      run: ./ci/install-eigen.sh /tmp/lib-install/eigen
      working-directory: scripts

    # Install Python dependencies to generate tests
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9.2'
    - name: Install Python Dependencies 
      run: | 
        python -m pip install -r requirements.txt
        python -m pip install casadi
      working-directory: scripts

    # Create the `gh-pages` branch if it doesn't exist already, check it out, 
    # and copy it to /tmp/staging.
    - name: Create staging area
      run: |
        rm -rf /tmp/staging
        git fetch origin gh-pages:gh-pages ||:
        git checkout gh-pages || \
        { git checkout --orphan gh-pages && git rm -rf . && git clean -fxd ; }
        cp -ar $GITHUB_WORKSPACE/ /tmp/staging
        git checkout ${GITHUB_REF##*/}

    # Generate the documentation and save it in /tmp/staging
    - name: Generate documentation
      run: ./scripts/ci/gen-docs.sh /tmp/staging
      env:
        CC: clang-10
        CXX: clang++-10
        CMAKE_PREFIX_PATH: "/tmp/lib-install/gtest:/tmp/lib-install/eigen"

    # Commit the new documentation, squash the commits, and push it to GitHub
    - name: Commit and push documention
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        commithash=$(git rev-parse HEAD)
        cd /tmp/staging
        git add .
        git commit -m "Documentation for ${commithash}" && \
        git reset $(git commit-tree HEAD^{tree} -m "Documentation for ${commithash}") && \
        git push -f origin gh-pages ||:
