name: CI Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: "/tmp/lib-install/gtest"
        key: ${{ runner.os }}-${{ hashFiles('scripts/ci/install-gtest.sh') }}
    - name: Install Google Test
      run: ./ci/install-gtest.sh /tmp/lib-install/gtest
      working-directory: scripts
    - uses: actions/cache@v2
      with:
        path: "/tmp/lib-install/eigen"
        key: ${{ runner.os }}-${{ hashFiles('scripts/ci/install-eigen.sh') }}
    - name: Install Eigen
      run: ./ci/install-eigen.sh /tmp/lib-install/eigen
      working-directory: scripts
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7 - 3.9'
    - name: Install Python Dependencies 
      run: python -m pip install -r requirements.txt
      working-directory: test/python
    - name: Create build directory
      run: mkdir -p build
    - name: CMake
      run: cmake .. -DCMAKE_BUILD_TYPE=Asan
      working-directory: build
      env:
        CC: clang-10
        CXX: clang++-10
        CMAKE_PREFIX_PATH: "/tmp/lib-install/gtest:/tmp/lib-install/eigen"
    - name: Build
      run: make -j4
      working-directory: build
    - name: Run tests
      run: ./test/tests --gtest_color=yes
      working-directory: build
