name: Python Wheels

on:
  workflow_dispatch:
  release:
    types: ['released', 'prereleased']

env:
  PACKAGE_VERSION: '1.0.0a8'
  PACKAGE_NAME: alpaqa
  MODULE_NAME: alpaqa
  C_EXTENSIONS: _alpaqa
  TWINE_REPOSITORY: pypi

jobs:
  generate-stubs:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    env:
      HOST: 'x86_64-centos7-linux-gnu'
      PYTHON_VERSION: '3.10'
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache
      CCACHE_DIR: /root/.ccache
    steps:
      # Git clone
      - name: Install git
        run: apt -y update && apt -y install --no-install-recommends git ca-certificates
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # Tools
      - name: Install tools
        uses: ./.github/workflows/toolchain
        with:
          host: ${{ env.HOST }}
          python-version: ${{ env.PYTHON_VERSION }}
          pypy: ''
      # Ccache
      - name: Prepare ccache directory
        run: mkdir -p "${{ env.CCACHE_DIR }}"
      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.HOST }}-ccache-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.HOST }}-ccache
      # Pip install dependencies
      - name: Install Python dependencies
        run: python${{ env.PYTHON_VERSION }} -m pip install -U pip build pybind11-stubgen py-build-cmake~=0.1.0
      # Build
      - name: Native build
        run: |
          host="${{ env.HOST }}"
          staging="/opt/$host"
          pbc_cli="python${{ env.PYTHON_VERSION }} -m py_build_cmake.cli"
          $pbc_cli -B native-build configure -- \
              -D CMAKE_C_COMPILER="$staging/x-tools/$host/bin/$host-gcc" \
              -D CMAKE_CXX_COMPILER="$staging/x-tools/$host/bin/$host-g++" \
              -D CMAKE_Fortran_COMPILER="$staging/x-tools/$host/bin/$host-gfortran" \
              -D USE_GLOBAL_PYBIND11=On \
              -D CMAKE_FIND_ROOT_PATH="$staging/pybind11;$staging/eigen-master;$staging/casadi"
          $pbc_cli -B native-build build -- -t ${{ env.C_EXTENSIONS }}
          $pbc_cli -B native-build install --component python_stubs -- --prefix "$PWD/staging/python"
          tar cf stubs.tar -C "$PWD/staging" python
      # Upload
      - name: Upload stubs
        uses: actions/upload-artifact@v3
        with:
          name: stubs
          retention-days: 1
          path: stubs.tar

  build-linux:
    needs: [generate-stubs]
    runs-on: ubuntu-latest
    container: 
      image: ubuntu:jammy
    strategy:
      matrix:
        pypy: ['', pypy]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        host: [x86_64-centos7-linux-gnu, armv7-neon-linux-gnueabihf, armv6-rpi-linux-gnueabihf, aarch64-rpi3-linux-gnu]
        include:
          - python-version: '3.8'
            pypy-version: '7.3.11'
          - python-version: '3.9'
            pypy-version: '7.3.12'
          - python-version: '3.10'
            pypy-version: '7.3.12'
        exclude:
          - pypy: pypy
            python-version: '3.11'
          - pypy: pypy
            python-version: '3.12'
          - pypy: pypy
            host: armv7-neon-linux-gnueabihf
          - pypy: pypy
            host: armv6-rpi-linux-gnueabihf
    env:
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache
      CCACHE_DIR: /root/.ccache
    steps:
      # Git clone
      - name: Install git
        run: apt -y update && apt -y install --no-install-recommends git ca-certificates
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # Tools
      - name: Install tools
        uses: ./.github/workflows/toolchain
        with:
          host: ${{ matrix.host }}
          python-version: ${{ matrix.python-version }}
          pypy: ${{ matrix.pypy }}
          pypy-version: ${{ matrix.pypy-version }}
      # Ccache
      - name: Prepare ccache directory
        run: mkdir -p "${{ env.CCACHE_DIR }}"
      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-${{ matrix.pypy }}${{ matrix.python-version }}-${{ matrix.host }}-ccache-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-${{ matrix.pypy }}${{ matrix.python-version }}-${{ matrix.host }}-ccache
      # Pip install dependencies
      - name: Install Python dependencies
        run: python${{ matrix.python-version }} -m pip install -U pip build pybind11-stubgen py-build-cmake~=0.0.16a2
      # Download stubs
      - name: Download stubs
        uses: actions/download-artifact@v3
        with:
          name: stubs
      - name: Extract stubs
        run: tar xf stubs.tar
      # Build
      - name: Build wheels
        run: |
          host="${{ matrix.host }}"
          staging="/opt/$host"
          cat > ninja-debug-release.cross.toml <<- EOF
          [cmake]
          config = ["Debug", "Release"]
          generator = "Ninja Multi-Config"
          [cmake.options]
          CMAKE_FIND_ROOT_PATH = "$staging/pybind11;$staging/eigen-master;$staging/casadi"
          USE_GLOBAL_PYBIND11 = "On"
          EOF
          python${{ matrix.python-version }} -m build -w . \
              -C--cross="$PWD/ninja-debug-release.cross.toml" \
              -C--cross="$staging/cmake/$host.py-build-cmake.cross.toml"
          python${{ matrix.python-version }} -m build -w python/alpaqa-debug \
              -C--cross="$PWD/ninja-debug-release.cross.toml" \
              -C--cross="$staging/cmake/$host.py-build-cmake.cross.toml" \
              -o dist-debug
        env:
          CFLAGS: '-static-libgcc'
          CXXFLAGS: '-static-libgcc -static-libstdc++'
      # Upload
      - name: Upload Wheels
        uses: actions/upload-artifact@v3
        with:
          name: whl-${{ matrix.pypy }}${{ matrix.python-version }}-linux
          retention-days: 1
          path: dist/*.whl
      - name: Upload debug Wheels
        uses: actions/upload-artifact@v3
        with:
          name: whl-${{ matrix.pypy }}${{ matrix.python-version }}-debug-linux
          retention-days: 1
          path: dist-debug/*.whl

  build-linux-src:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    env:
      HOST: 'x86_64-centos7-linux-gnu'
      PYTHON_VERSION: '3.10'
    steps:
      # Git clone
      - name: Install git
        run: apt -y update && apt -y install --no-install-recommends git ca-certificates
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # Tools
      - name: Install tools
        uses: ./.github/workflows/toolchain
        with:
          host: ${{ env.HOST }}
          python-version: ${{ env.PYTHON_VERSION }}
          pypy: ''
      # Pip install dependencies
      - name: Install Python dependencies
        run: python${{ env.PYTHON_VERSION }} -m pip install -U pip build
      # Build
      - name: Build wheels
        run: |
          host="${{ env.HOST }}"
          staging="/opt/$host"
          cat > ninja-debug.cross.toml <<- EOF
          [cmake]
          config = ["Debug"]
          generator = "Ninja Multi-Config"
          [cmake.options]
          CMAKE_FIND_ROOT_PATH = "$staging/pybind11;$staging/eigen-master;$staging/casadi"
          USE_GLOBAL_PYBIND11 = "On"
          EOF
          python${{ env.PYTHON_VERSION }} -m build . \
              -C--cross="$PWD/ninja-debug.cross.toml" \
              -C--cross="$staging/cmake/$host.py-build-cmake.cross.toml"
        env:
          CFLAGS: '-static-libgcc'
          CXXFLAGS: '-static-libgcc -static-libstdc++'
      # Upload
      - name: Upload source
        uses: actions/upload-artifact@v3
        with:
          name: src-dist
          retention-days: 1
          path: dist/*.tar.gz

  test-linux:
    needs: [build-linux]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}-bullseye
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/download-artifact@v3
        with:
          name: whl-${{ matrix.python-version }}-linux
          path: dist
      - name: Test
        run: |
          python3 -m pip install -U pip cmake ninja
          python3 -m pip install --find-links=dist "${PACKAGE_NAME}[test]==${PACKAGE_VERSION}"
          pytest -rP


  build-windows:
    needs: [generate-stubs]
    runs-on: windows-2022
    strategy:
      matrix:
        arch: ['AMD64', 'ARM64', 'x86']
        python-id: ['cp38-*', 'cp39-*', 'cp310-*', 'cp311-*']
        include:
          - arch: 'AMD64'
            python-id: 'pp38-*'
          - arch: 'AMD64'
            python-id: 'pp39-*'
          - arch: 'AMD64'
            python-id: 'pp310-*'
        exclude:
          - arch: 'ARM64'
            python-id: 'cp38-*'
    env:
      CXXFLAGS: "/bigobj"
      CFLAGS: "/bigobj"
      PYTHONUTF8: 1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache dependencies
        id: cache-dep
        uses: actions/cache@v3
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('scripts/install-eigen.ps1', 'scripts/install-casadi-static.ps1') }}
      - name: Install Python dependencies
        if: steps.cache-dep.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          mkdir $env:VIRTUAL_ENV
          ./scripts/install-eigen.ps1
          ./scripts/install-casadi-static.ps1
        env:
          VIRTUAL_ENV: ${{ github.workspace }}/deps
          CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/scripts/toolchains/Win-${{ matrix.arch }}.cmake
      # Download stubs
      - name: Download stubs
        if: ${{ matrix.arch == 'ARM64' }}
        uses: actions/download-artifact@v3
        with:
          name: stubs
      - name: Extract stubs
        if: ${{ matrix.arch == 'ARM64' }}
        run: tar xf stubs.tar
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        with:
          output-dir: dist
        env:
          CIBW_BUILD: ${{ matrix.python-id }}
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_TEST_SKIP: "*-{win32,win_arm64} pp*" # no CasADi binaries
          CMAKE_PREFIX_PATH: ${{ github.workspace }}/deps
          CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/scripts/toolchains/Win-${{ matrix.arch }}.cmake
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: whl-windows
          retention-days: 1
          path: dist/*.whl


  build-macos:
    runs-on: macos-12
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    env:
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache
      CCACHE_DIR: /tmp/.ccache
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        id: python
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ccache
        run: brew install ccache && ccache --version
      - name: Prepare ccache directory
        run: mkdir -p "${{ env.CCACHE_DIR }}"
      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-${{ matrix.python-version }}-ccache-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-${{ matrix.python-version }}-ccache
      - name: Cache Virtual Environment
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: py-venv
          key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{ hashFiles('scripts/install-eigen.sh', 'scripts/install-casadi-static.sh') }}
      - name: Install Python dependencies 
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv py-venv
          source ./py-venv/bin/activate
          python -m pip install -U pip build cmake ninja
          ./scripts/install-eigen.sh
          ./scripts/install-casadi-static.sh
      - name: Build
        run: |
          source ./py-venv/bin/activate
          CMAKE_PREFIX_PATH="$VIRTUAL_ENV:$CMAKE_PREFIX_PATH" \
          _PYTHON_HOST_PLATFORM='macosx-10.9-universal2' \
          ARCHFLAGS='-arch arm64 -arch x86_64' \
              python -m build -w .
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: whl-${{ matrix.python-version }}-macos
          retention-days: 1
          path: dist/*.whl

  test-macos:
    needs: [build-macos]
    runs-on: macos-12
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        name: Install Python
        with: 
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@v3
        with:
          name: whl-${{ matrix.python-version }}-macos
          path: dist
      - name: Test
        run: |
          python3 -m pip install -U pip cmake ninja
          python3 -m pip install --find-links=dist "${PACKAGE_NAME}[test]==${PACKAGE_VERSION}"
          pytest -rP


  release:
    if: ${{ github.event.action == 'released' || github.event.action == 'prereleased' }}
    needs: [test-linux, build-linux-src, build-windows, test-macos]
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}:${{ matrix.python-version }}${{ matrix.python-version-suffix }}-bullseye
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        python-version-suffix: ['']
        pypy: ['']
        container: ['python']
        include:
          - python-version: '3.8'
            pypy: 'pypy'
            container: 'pypy'
          - python-version: '3.9'
            pypy: 'pypy'
            container: 'pypy'
          - python-version: '3.10'
            pypy: 'pypy'
            container: 'pypy'
          - python-version: '3.12'
            python-version-suffix: '-rc'
            pypy: ''
            container: 'python'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: whl-${{ matrix.pypy }}${{ matrix.python-version }}-linux
          path: dist
      - uses: actions/download-artifact@v3
        with:
          name: whl-${{ matrix.pypy }}${{ matrix.python-version }}-debug-linux
          path: dist
      - uses: actions/download-artifact@v3
        if: ${{ matrix.python-version == '3.11' && !matrix.pypy }}
        with:
          name: whl-windows
          path: dist
      - uses: actions/download-artifact@v3
        if: ${{ matrix.python-version != '3.12' && !matrix.pypy }}
        with:
          name: whl-${{ matrix.python-version }}-macos
          path: dist
      - name: Install Twine
        run: python -m pip install -U pip twine
      - name: Check Wheel metadata
        run: python -m twine check dist/*.whl
      - name: Install package
        run: python -m pip install --no-deps --no-index --find-links=dist ${PACKAGE_NAME}==${PACKAGE_VERSION}
      - name: Check package version
        run: |
          [ "${{ github.event.release.tag_name }}" == $(python -c 'from importlib.metadata import version as v; print(v("${{ env.MODULE_NAME }}"))') ]
        shell: bash
      - name: Upload Wheels to PyPI
        run: python -m twine upload -r ${{ env.TWINE_REPOSITORY }} dist/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PyPI }}
      - uses: actions/download-artifact@v3
        if: ${{ matrix.python-version == '3.11' && !matrix.pypy }}
        with:
          name: src-dist
          path: dist
      - name: Upload source to PyPI
        if: ${{ matrix.python-version == '3.11' && !matrix.pypy }}
        run: python -m twine upload -r ${{ env.TWINE_REPOSITORY }} dist/*.tar.gz
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PyPI }}
